using UnityEngine;
using System;

namespace Overun.Waves
{
    /// <summary>
    /// Runtime data for an individual wave.
    /// Generated by WaveManager from WaveConfig.
    /// </summary>
    [Serializable]
    public class WaveData
    {
        [SerializeField] private int _waveNumber;
        [SerializeField] private int _enemyCount;
        [SerializeField] private bool _isBossWave;
        [SerializeField] private bool _canSpawnElites;
        
        // Runtime tracking
        private int _enemiesSpawned;
        private int _enemiesKilled;
        
        public int WaveNumber => _waveNumber;
        public int EnemyCount => _enemyCount;
        public bool IsBossWave => _isBossWave;
        public bool CanSpawnElites => _canSpawnElites;
        
        public int EnemiesSpawned => _enemiesSpawned;
        public int EnemiesKilled => _enemiesKilled;
        public int EnemiesRemaining => _enemyCount - _enemiesKilled;
        public int EnemiesAlive => _enemiesSpawned - _enemiesKilled;
        public bool AllSpawned => _enemiesSpawned >= _enemyCount;
        public bool IsComplete => _enemiesKilled >= _enemyCount;
        public float Progress => _enemyCount > 0 ? (float)_enemiesKilled / _enemyCount : 1f;
        
        public WaveData(int waveNumber, WaveConfig config)
        {
            _waveNumber = waveNumber;
            _enemyCount = config.GetEnemyCountForWave(waveNumber);
            _isBossWave = config.IsBossWave(waveNumber);
            _canSpawnElites = config.CanSpawnElites(waveNumber);
            _enemiesSpawned = 0;
            _enemiesKilled = 0;
        }
        
        public void OnEnemySpawned()
        {
            _enemiesSpawned++;
        }
        
        public void OnEnemyKilled()
        {
            _enemiesKilled++;
        }
        
        public void Reset()
        {
            _enemiesSpawned = 0;
            _enemiesKilled = 0;
        }
        
        public override string ToString()
        {
            return $"Wave {_waveNumber}: {_enemiesKilled}/{_enemyCount} killed" +
                   (_isBossWave ? " [BOSS]" : "");
        }


    }
}
